name: Build DLL

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        game: [GW1, GW2, BFN]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          choco install visualstudio2026buildtools `
            --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" `
            -y
          choco install cmake -y

      - name: Build
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          cd Server
          mkdir build
          cmake --fresh build -G "Visual Studio 18 2026" -DCYPRESS_${{ matrix.game }}=ON
          cmake --build build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: cypress_${{ matrix.game }}
          path: Server/build/Release/cypress_${{ matrix.game }}.dll
